#!/bin/bash
CWD=$(realpath $(cd "$(dirname "$0")"; pwd))
if [[ $# -lt 1 ]]; then
    echo "USAGE:./$(basename "$0") <mysql|redis|mysql-redis>"
    exit -1
fi

function linkObject {
    media=$1
    objectSourceDir=$2
    for object in `ls ${objectSourceDir}/router/*.${media}.js`
    do
        targetObject=$(echo "$object" | sed -r "s/.${media}././g")
        ln -sf ${object} ${targetObject}
    done
}

function linkRelation {
    media=$1
    relationSourceDir=$2
    for subject in `ls ${relationSourceDir}/router`
    do
        if [[ ! -d ${relationSourceDir}/schema/${subject} ]]; then
            echo "expect ${relationSourceDir}/router/${subject} to be a folder"
        fi
        for object in `ls ${relationSourceDir}/router/${subject}/*.${media}.js`
        do
            targetObject=$(echo "$object" | sed -r "s/.${media}././g")
            ln -sf ${object} ${targetObject}
        done
    done
}

sourceDir=${CWD}/../config
linkObject $1 ${sourceDir}/object
linkRelation $1 ${sourceDir}/relation
echo "done"
